const data = [
    {
        id : 1,
        brand: "1percentStudio",
        website:"https://1percnt-studio.vercel.app/",
        tools:["reactjs","Tailwind css", "react-dom"],
        description:"got a design refrence and developed pixek perfect desin for a creative agency which focuses on videography, photography, graphic design ",
        poster1: "public/assets/screencapture-1percnt-studio-vercel-app-2024-07-15-23_14_46.png",
        poster2: "public/assets/screencapture-1percnt-studio-vercel-app-2024-07-15-23_18_23.png",
        poster3: "public/assets/screencapture-1percnt-studio-vercel-app-2024-07-15-23_18_24.png",
        poster4: "public/assets/screencapture-1percnt-studio-vercel-app-2024-07-15-23_18_24.png",
        poster5: "public/assets/screencapture-1percnt-studio-vercel-app-2024-07-15-23_18_25.png",
    },
    {
        id : 2,
        brand: "kids world",
        website:"https://kids-school-web.netlify.app/",
        tools:["reactjs","Tailwind css", "react-dom"],
        description:"got a design refrence and developed pixek perfect desin for a creative agency which focuses on videography, photography, graphic design ",
        poster1: "public/assets/screencapture-kids-school-web-netlify-app-2024-07-15-23_22_41.png",
        poster2: "public/assets/screencapture-kids-school-web-netlify-app-2024-07-15-23_22_40.png",
        poster3: "public/assets/screencapture-kids-school-web-netlify-app-2024-07-15-23_22_40 - Copy.png",
        poster4: "",
        poster5: "",
    },
    {
        id : 3,
        brand: "hackathon",
        website:"https://analytics-dashboard-geepay.netlify.app/",
        tools:["reactjs","Tailwind css", "react-dom"],
        description:"got a design refrence and developed pixek perfect desin for a creative agency which focuses on videography, photography, graphic design ",
        poster1: "public/assets/screencapture-analytics-dashboard-geepay-netlify-app-2024-07-15-23_21_40.png",
        poster2: "",
        poster3: "",
        poster4: "",
        poster5: "",
    },
]
export default data;